buildscript {
	ext {
		serenityCoreVersion = '3.1.15'
		serenityCucumberVersion = '3.1.15'
		cucumberVersion = '7.15.0'
		cucumberJunitVersion = '7.15.0'
		junitVersion = '4.13.1'
		restAssuredVersion = '5.4.0'
		springBeansVersion = '5.3.34'
		gatlingVersion = '3.9.2'
		scalaLibraryVersion = '2.13.12'
		lombokVersion = '1.18.30'
        wireMockVersion = '3.10.0'
        wireMockStandaloneVersion = '3.0.1'
		mySqlVersion = '8.1.0'
		postgreSqlVersion = '42.6.0'
		zaxxerHikariCP = '5.0.1'
	}

	dependencies {
		classpath "net.serenity-bdd:serenity-gradle-plugin:${serenityCoreVersion}"
		classpath "com.github.tomakehurst:wiremock-standalone:${wireMockStandaloneVersion}"
	}
}

plugins {
	id 'java'
	id 'scala'
	id 'org.springframework.boot' version '3.2.2'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'io.gatling.gradle' version "3.9.2"
}

apply plugin: 'net.serenity-bdd.aggregator'
apply plugin: 'scala'

sourceSets {
	wiremock {
		java.srcDir 'src/wiremock/java'
		resources.srcDir 'src/wiremock/resources'
		compileClasspath += main.output
		runtimeClasspath += main.output
	}
}

configurations {
	wiremockImplementation.extendsFrom implementation
	testImplementation.extendsFrom implementation
}

group = 'com.ratnakar.practice'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	// Make testImplementation inherit from implementation
	testImplementation.extendsFrom implementation
	// Inherit compileOnly dependencies (e.g., Lombok)
	testImplementation.extendsFrom compileOnly
	// Inherit runtime dependencies (DB drivers, etc.)
	testImplementation.extendsFrom runtimeOnly
	// Inherit annotation processors if required
	testAnnotationProcessor.extendsFrom annotationProcessor
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot Dependencies
	implementation "org.springframework.boot:spring-boot-starter-data-jpa"
	implementation "org.springframework.boot:spring-boot-starter-validation"
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.springframework.boot:spring-boot-starter-jdbc"
	// spring-boot-starter-data-rest is used to automatically expose Spring Data repositories as RESTful APIs (CRUD endpoints) without writing controllers.
	implementation "org.springframework.boot:spring-boot-starter-data-rest"
	implementation "org.apache.commons:commons-dbcp2"
	implementation "jakarta.annotation:jakarta.annotation-api"
	// Optional: HikariCP (Spring Boot uses it by default)
	implementation "com.zaxxer:HikariCP:${zaxxerHikariCP}"
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// Database MySQL & PostgreSQL drivers
	runtimeOnly "com.mysql:mysql-connector-j:${mySqlVersion}" // MYSQL
	runtimeOnly "org.postgresql:postgresql:${postgreSqlVersion}"  // POSTGRESQL

	compileOnly "org.projectlombok:lombok"
	// runtimeOnly 'com.h2database:h2'
	annotationProcessor "org.projectlombok:lombok"
	implementation "org.projectlombok:lombok:${lombokVersion}"
	// Wiremock-standalone
	implementation "org.wiremock:wiremock-standalone:${wireMockStandaloneVersion}"
	// Junit and Component testing dependencies
	testImplementation "org.springframework.boot:spring-boot-starter-test"
    // wiremock
    testImplementation "org.wiremock:wiremock:${wireMockVersion}"
	testCompileOnly "org.projectlombok:lombok"
	testAnnotationProcessor "org.projectlombok:lombok"
}

configurations{
	[apiElements, runtimeElements].each {
		it.outgoing.artifacts.removeIf { it.buildDependencies.getDependencies(null).contains(jar)}
		it.outgoing.artifact(bootJar)
	}
}

tasks.register('runWireMock', JavaExec) {
	description = 'Runs the WireMock standalone server'
	classpath = sourceSets.wiremock.runtimeClasspath
	mainClass = 'com.ratnakar.wiremock.runner' // Ensure this is your correct package path
}

jar{
	enabled = false
}

allprojects{
	apply plugin: 'java'
	tasks.withType(Copy).all{
		duplicatesStrategy 'exclude'
	}
}
