// Package declaration: Organizes service implementation classes together
// Service implementations contain the actual business logic that interfaces define
package com.ratnakar.practice.TicketBookingAPI.service;

// Import custom exceptions for handling specific error scenarios
import com.ratnakar.practice.TicketBookingAPI.exception.BookingException;
// Import model/entity classes used in business logic
import com.ratnakar.practice.TicketBookingAPI.model.Booking;
import com.ratnakar.practice.TicketBookingAPI.model.BookingData;
import com.ratnakar.practice.TicketBookingAPI.model.User;
// Import repository interfaces for data access
import com.ratnakar.practice.TicketBookingAPI.repository.BookingRepository;
import com.ratnakar.practice.TicketBookingAPI.repository.UserRepository;
// Spring Framework annotations for dependency injection and service layer
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
// Java Collections and Stream API for data processing
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * BookingServiceImpl - Implementation of BookingService interface.
 *
 * @Service annotation marks this class as a Spring Service.
 * A service is a Spring-managed bean that contains business logic.
 *
 * This annotation:
 * 1. Enables component scanning (Spring detects and instantiates this bean)
 * 2. Indicates this class holds business logic (as opposed to @Component)
 * 3. Allows dependency injection into this class
 * 4. Makes this class a candidate for Spring's transaction management
 *
 * implements BookingService: Provides concrete implementation for all
 * methods defined in the BookingService interface.
 */
@Service
public class BookingServiceImpl implements BookingService {

    /**
     * Dependency Injection of BookingRepository.
     * @Autowired tells Spring to inject an instance of BookingRepository.
     * BookingRepository is a Spring Data JPA interface that provides
     * database operations for Booking entities.
     *
     * Field injection is used here (injection directly into field).
     * Alternatives: Constructor injection (recommended) or Setter injection.
     */
    @Autowired
    private BookingRepository bookingRepository;

    /**
     * Dependency Injection of UserRepository.
     * UserRepository provides database operations for User entities.
     * Needed to validate that users exist before creating bookings.
     */
    @Autowired
    private UserRepository userRepository;

    /**
     * Constant for business rule: Maximum tickets per booking.
     * Using a constant makes the code:
     * 1. More readable (named constant instead of magic number)
     * 2. Maintainable (change in one place affects all uses)
     * 3. Self-documenting (name explains the value)
     *
     * static: Belongs to class, not instance (shared across all instances)
     * final: Cannot be changed (constant)
     */
    private static final int MAX_TICKETS = 100;

    /**
     * Implementation of bookTicket method from BookingService interface.
     * Creates a new booking for a user with validation.
     *
     * @param userId Unique identifier of the user making the booking
     * @param bookedByName Name of person booking is for
     * @param movieName Name of movie to book tickets for
     * @param numberOfTickets Number of tickets to book
     * @return Booking entity that was created and saved
     * @throws Exception if validation fails or user not found
     *
     * Note: This method throws generic Exception. Consider throwing
     * specific exceptions like IllegalArgumentException, BookingException, etc.
     */
    @Override
    public Booking bookTicket(String userId, String bookedByName, String movieName, int numberOfTickets) throws Exception {

        // Business rule validation: Ticket count must be between 1 and MAX_TICKETS
        // This prevents unreasonable bookings and enforces system limits
        if (numberOfTickets < 1 || numberOfTickets > MAX_TICKETS) {
            throw new Exception("You can book between 1 and 100 tickets.");
        }

        // Validate that the user exists in the system
        // userRepository.findById() returns Optional<User> - container that may or may not contain a User
        // orElseThrow() provides a lambda expression that creates an exception if user not found
        // This is a functional programming approach to handle null safely
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new Exception("User not found with ID: " + userId));

        // Create a new Booking entity instance
        // Using default constructor (generated by Lombok @NoArgsConstructor)
        Booking booking = new Booking();

        // Set the user relationship (Many-to-One: booking belongs to a user)
        booking.setUser(user);
        // Set the name of person booking is for
        booking.setBookedByName(bookedByName);
        // Set the movie name
        booking.setMovieName(movieName);
        // Set the number of tickets
        booking.setNumberOfTickets(numberOfTickets);

        // Save the booking to database using Spring Data JPA
        // bookingRepository.save() performs INSERT operation
        // Returns the saved entity with generated ID (if using auto-increment)
        return bookingRepository.save(booking);
    }

    /**
     * Implementation of updateBooking method.
     * Updates an existing booking with new ticket count.
     *
     * @param bookingId ID of booking to update
     * @param newNumberOfTickets New number of tickets
     * @return Updated Booking entity
     *
     * @Transactional annotation ensures this method runs within a database transaction.
     * Transaction management:
     * 1. If method completes successfully, transaction is committed
     * 2. If RuntimeException is thrown, transaction is rolled back
     * 3. Creates a persistence context (entity manager session)
     *
     * Default transaction attributes:
     * - Propagation: REQUIRED (joins existing transaction or creates new one)
     * - Isolation: DEFAULT (uses database default, usually READ_COMMITTED)
     * - Read-only: false (allows write operations)
     * - Timeout: uses system default
     * - Rollback for: RuntimeException (unchecked exceptions)
     */
    @Override
    @Transactional
    public Booking updateBooking(Long bookingId, int newNumberOfTickets) {

        // Validate new ticket count against business rules
        if (newNumberOfTickets < 1 || newNumberOfTickets > MAX_TICKETS) {
            // Throwing BookingException (unchecked) triggers transaction rollback
            throw new BookingException("You can book between 1 and 100 tickets.");
        }

        // Find booking by ID or throw exception if not found
        // bookingRepository.findById() returns Optional<Booking>
        // orElseThrow() throws BookingException if Optional is empty
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() ->
                        new BookingException("Booking not found with id: " + bookingId));

        // Update the number of tickets in the booking entity
        // Since we're in a transactional context and the entity is managed
        // (attached to persistence context), this change will be automatically
        // detected and persisted when transaction commits (dirty checking)
        booking.setNumberOfTickets(newNumberOfTickets);

        // Explicitly save the entity (optional in transactional context)
        // In JPA with @Transactional, changes to managed entities are automatically
        // flushed to database when transaction commits. However, calling save()
        // explicitly is good practice for clarity and ensures immediate persistence
        // Returns the updated entity (with same ID but updated fields)
        return bookingRepository.save(booking);
    }

    /**
     * Implementation of cancelBooking method.
     * Deletes a booking from the system.
     *
     * @param bookingId ID of booking to cancel
     * @throws Exception if booking not found or deletion fails
     *
     * Note: This method doesn't have @Transactional annotation but should.
     * Delete operations should be transactional to ensure data consistency.
     */
    @Override
    public void cancelBooking(Long bookingId) throws Exception {
        // Check if booking exists before attempting deletion
        // bookingRepository.existsById() returns boolean (true if exists)
        // This is a defensive check to provide a better error message
        if (!bookingRepository.existsById(bookingId)) {
            throw new Exception("Booking not found with id: " + bookingId);
        }
        // Delete the booking by ID
        // bookingRepository.deleteById() performs DELETE operation
        // If booking doesn't exist, throws EmptyResultDataAccessException
        bookingRepository.deleteById(bookingId);
    }

    /**
     * Implementation of getAllBookings method.
     * Retrieves all bookings and converts them to BookingData DTOs.
     *
     * @return List<BookingData> simplified view of all bookings
     *
     * @Transactional(readOnly = true) annotation:
     * - readOnly = true: Optimizes for read-only operations
     * - No write operations allowed in this transaction
     * - May provide performance benefits (no dirty checking, flush not required)
     * - Still provides transaction boundaries for consistency
     */
    @Transactional(readOnly = true)
    @Override
    public List<BookingData> getAllBookings() {
        // Get all bookings from database
        // bookingRepository.findAll() returns List<Booking> (all entities)
        // This could be inefficient for large datasets (consider pagination)
        return bookingRepository.findAll()
                // Convert List<Booking> to Stream<Booking>
                // Stream API provides functional-style operations on collections
                .stream()
                // Map each Booking entity to BookingData DTO
                // Method reference: BookingData::new is equivalent to
                // booking -> new BookingData(booking)
                // Uses constructor of BookingData that takes Booking as parameter
                .map(BookingData::new) // now Booking matches constructor
                // Collect Stream<BookingData> back to List<BookingData>
                // Collectors.toList() accumulates elements into a List
                .collect(Collectors.toList());
    }

    // Note: Missing transaction on bookTicket and cancelBooking methods
    // Consider adding @Transactional to ensure data consistency

    // Note: Additional business logic that could be added:

    /**
     * Example: Check seat availability before booking
     * private boolean checkSeatAvailability(String movieName, int requestedTickets) {
     *     int bookedTickets = bookingRepository.sumTicketsByMovie(movieName);
     *     return (bookedTickets + requestedTickets) <= THEATER_CAPACITY;
     * }
     *
     * Example: Calculate booking cost
     * private double calculateCost(int numberOfTickets, String movieName) {
     *     double ticketPrice = getTicketPrice(movieName);
     *     return numberOfTickets * ticketPrice;
     * }
     *
     * Example: Send confirmation email
     * private void sendConfirmationEmail(User user, Booking booking) {
     *     // Email sending logic
     * }
     */

    /**
     * SECURITY CONSIDERATIONS:
     * 1. Validate that user has permission to book/cancel/update
     * 2. Consider adding rate limiting to prevent abuse
     * 3. Log important operations for audit trail
     *
     * PERFORMANCE CONSIDERATIONS:
     * 1. getAllBookings() could return huge dataset - add pagination
     * 2. Consider caching frequently accessed data
     * 3. Use database indexes for frequently queried columns
     *
     * ERROR HANDLING IMPROVEMENTS:
     * 1. Use specific exception types instead of generic Exception
     * 2. Add more detailed error messages with context
     * 3. Consider using exception hierarchy for different error types
     */
}